### ISSUE TITLE
[EPIC] P2P Blocksync Testing

### ISSUE THREAD

**Issue by nashqueue** [evstack/ev-node#1102]
```[tasklist]
### Integrations Tests
- [ ] Gossip Block with no Transaction
- [ ] Gossip Block with 1 Transaction
- [ ] Gossip Block with a lot of Transactions
- [ ] Speed Test for benchmarks
- [ ] https://github.com/rollkit/rollkit/issues/1104
- [ ] https://github.com/rollkit/rollkit/issues/1103
- [ ] Run cosmos-sdk unit/integration tests with Rollkit
- [ ] Add load tests to discover the lowest block time that can be supported for different configurations
- [ ] Larger Network tests
```

**Comment by tac0turtle** [comment]
we have a few tests that cover this now, we can close it
